// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "../contracts/ZKVerifier.sol";

/// @notice Deploy the Groth16 ZK verifier (generated by snarkjs).
///
/// PREREQUISITE: Run `bash circuits/setup.sh` FIRST.
/// That script overwrites contracts/ZKVerifier.sol with the real verifier.
/// If you deploy before running setup.sh, the stub returns false for all proofs.
///
/// Usage:
///   forge script script/DeployVerifier.s.sol \
///     --rpc-url $BSC_TESTNET_RPC \
///     --broadcast \
///     --private-key $PRIVATE_KEY
///
/// Save the printed verifier address — pass it to DeployEscrowWithZK.s.sol.
contract DeployVerifier is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");

        vm.startBroadcast(deployerPrivateKey);
        Groth16Verifier verifier = new Groth16Verifier();
        vm.stopBroadcast();

        console.log("=== Groth16Verifier deployed ===");
        console.log("Address:", address(verifier));
        console.log("");
        console.log("Set this in your .env:");
        console.log("  ZK_VERIFIER_ADDRESS=", address(verifier));
        console.log("");
        console.log("Next: forge script script/DeployEscrowWithZK.s.sol --broadcast");
    }
}
