// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IZKVerifier
/// @notice Interface for Groth16 verifier contracts generated by snarkjs.
/// @dev The function signature matches the output of:
///      `snarkjs zkey export solidityverifier`
///      Public inputs array size (1) must match the circuit's public signal count.
interface IZKVerifier {
    /// @notice Verify a Groth16 proof.
    /// @param a  Proof point A  [x, y]
    /// @param b  Proof point B  [[x1,x2],[y1,y2]]
    /// @param c  Proof point C  [x, y]
    /// @param input Public signals. input[0] = zkHash (Poseidon field element)
    /// @return true if the proof is valid
    function verifyProof(
        uint256[2]  calldata a,
        uint256[2][2] calldata b,
        uint256[2]  calldata c,
        uint256[1]  calldata input
    ) external view returns (bool);
}
